In [4]:
import os
os.getcwd()

'c:\\Users\\Hp\\Desktop\\Projects\\10Academy\\insurance-risk-analytics\\insurance-risk-analytics\\insurance-risk-analytics\\notebooks'

In [5]:
df = pd.read_csv("../data/insurance_data.csv")

In [8]:
import os
print(os.getcwd())

c:\Users\Hp\Desktop\Projects\10Academy\insurance-risk-analytics\insurance-risk-analytics\insurance-risk-analytics\notebooks

In [9]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path().resolve().parent   # goes from notebooks → project root
DATA_PATH = BASE_DIR / "data" / "insurance_data.csv"

df = pd.read_csv(DATA_PATH)
df.head()

,CustomerID,Age,Gender,Province,VehicleType,AnnualIncome,RiskScore,AnnualPremium,Deductible,NCD,...,Claimed,ClaimAmount,TotalPremium,TotalClaims,CoverType,AutoMake,VehicleModel,CustomValueEstimate,ZipCode,TransactionDate
0,AC-100000,56,Male,Addis Ababa,Sedan,147270,61,2346,500,30,...,False,0.0,2346,0.0,Comprehensive,Lifan,620,32238,10002,2024-05-10
1,AC-100001,69,Female,Addis Ababa,SUV,74640,57,2334,500,0,...,True,9883.0,2334,9883.0,Comprehensive,Suzuki,Grand Vitara,52510,10001,2024-08-13
2,AC-100002,46,Male,Oromia,Sedan,70555,42,1697,250,20,...,False,0.0,1697,0.0,Third Party Fire & Theft,Lifan,620,26523,20001,2025-03-17
3,AC-100003,32,Female,Somali,Sedan,89398,63,2370,500,20,...,True,12134.0,2370,12134.0,Comprehensive,Toyota,Corolla,27036,40005,2025-03-17
4,AC-100004,60,Female,Tigray,SUV,78475,69,2582,500,0,...,False,0.0,2582,0.0,Comprehensive,Toyota,RAV4,58348,50002,2024-11-10

In [10]:
import os

os.chdir("..")  # move from notebooks → root
df = pd.read_csv("data/insurance_data.csv")

In [11]:
Path().resolve().parent

WindowsPath('C:/Users/Hp/Desktop/Projects/10Academy/insurance-risk-analytics/insurance-risk-analytics')

In [13]:
from pathlib import Path

p = Path("C:/Users/Hp/Desktop/Projects/10Academy/insurance-risk-analytics")
print(p.exists())
print(list(p.iterdir()))

True
[WindowsPath('C:/Users/Hp/Desktop/Projects/10Academy/insurance-risk-analytics/insurance-risk-analytics'), WindowsPath('C:/Users/Hp/Desktop/Projects/10Academy/insurance-risk-analytics/venv')]

In [14]:
for x in p.rglob("insurance_data.csv"):
    print(x)

C:\Users\Hp\Desktop\Projects\10Academy\insurance-risk-analytics\insurance-risk-analytics\insurance-risk-analytics\data\insurance_data.csv

In [15]:
from pathlib import Path
import pandas as pd

# find project root automatically
BASE_DIR = Path.cwd()

while not (BASE_DIR / "data" / "insurance_data.csv").exists():
    BASE_DIR = BASE_DIR.parent

DATA_PATH = BASE_DIR / "data" / "insurance_data.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,CustomerID,Age,Gender,Province,VehicleType,AnnualIncome,RiskScore,AnnualPremium,Deductible,NCD,...,Claimed,ClaimAmount,TotalPremium,TotalClaims,CoverType,AutoMake,VehicleModel,CustomValueEstimate,ZipCode,TransactionDate
0,AC-100000,56,Male,Addis Ababa,Sedan,147270,61,2346,500,30,...,False,0.0,2346,0.0,Comprehensive,Lifan,620,32238,10002,2024-05-10
1,AC-100001,69,Female,Addis Ababa,SUV,74640,57,2334,500,0,...,True,9883.0,2334,9883.0,Comprehensive,Suzuki,Grand Vitara,52510,10001,2024-08-13
2,AC-100002,46,Male,Oromia,Sedan,70555,42,1697,250,20,...,False,0.0,1697,0.0,Third Party Fire & Theft,Lifan,620,26523,20001,2025-03-17
3,AC-100003,32,Female,Somali,Sedan,89398,63,2370,500,20,...,True,12134.0,2370,12134.0,Comprehensive,Toyota,Corolla,27036,40005,2025-03-17
4,AC-100004,60,Female,Tigray,SUV,78475,69,2582,500,0,...,False,0.0,2582,0.0,Comprehensive,Toyota,RAV4,58348,50002,2024-11-10

In [16]:
df.shape
df.columns
df.head()

,CustomerID,Age,Gender,Province,VehicleType,AnnualIncome,RiskScore,AnnualPremium,Deductible,NCD,...,Claimed,ClaimAmount,TotalPremium,TotalClaims,CoverType,AutoMake,VehicleModel,CustomValueEstimate,ZipCode,TransactionDate
0,AC-100000,56,Male,Addis Ababa,Sedan,147270,61,2346,500,30,...,False,0.0,2346,0.0,Comprehensive,Lifan,620,32238,10002,2024-05-10
1,AC-100001,69,Female,Addis Ababa,SUV,74640,57,2334,500,0,...,True,9883.0,2334,9883.0,Comprehensive,Suzuki,Grand Vitara,52510,10001,2024-08-13
2,AC-100002,46,Male,Oromia,Sedan,70555,42,1697,250,20,...,False,0.0,1697,0.0,Third Party Fire & Theft,Lifan,620,26523,20001,2025-03-17
3,AC-100003,32,Female,Somali,Sedan,89398,63,2370,500,20,...,True,12134.0,2370,12134.0,Comprehensive,Toyota,Corolla,27036,40005,2025-03-17
4,AC-100004,60,Female,Tigray,SUV,78475,69,2582,500,0,...,False,0.0,2582,0.0,Comprehensive,Toyota,RAV4,58348,50002,2024-11-10

In [17]:
import pandas as pd

df = pd.read_csv("data/insurance_data.csv")

cleaned_df = df.dropna()

cleaned_df.to_csv("data/insurance_data_cleaned.csv", index=False)

In [19]:
import numpy as np
import pandas as pd

In [20]:
df['HasClaim'] = np.where(df['TotalClaims'] > 0, 1, 0)
df['Margin'] = df['TotalPremium'] - df['TotalClaims']

In [21]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
df['HasClaim'] = np.where(df['TotalClaims'] > 0, 1, 0)

df['Margin'] = df['TotalPremium'] - df['TotalClaims']

In [23]:
province_groups = [group['HasClaim'].values for _, group in df.groupby('Province')]

In [24]:
from scipy import stats

f_stat, p_value = stats.f_oneway(*province_groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

F-statistic: 2.115894461137008
P-value: 0.07608306716022667

In [25]:
gender_table = pd.crosstab(df['Gender'], df['HasClaim'])
gender_table

HasClaim     0    1
Gender
Female    4348  790
Male      4117  745

In [26]:
chi2, p_value, dof, expected = stats.chi2_contingency(gender_table)

print("Chi-square:", chi2)
print("P-value:", p_value)

Chi-square: 0.0020563626938139516
P-value: 0.9638306173980254

In [27]:
gender_table = pd.crosstab(df['Gender'], df['HasClaim'])
gender_table

HasClaim     0    1
Gender
Female    4348  790
Male      4117  745

In [28]:
from scipy import stats

chi2, p_value, dof, expected = stats.chi2_contingency(gender_table)

print("Chi-square:", chi2)
print("P-value:", p_value)

Chi-square: 0.0020563626938139516
P-value: 0.9638306173980254

In [30]:
province_f_stat, province_p_value = stats.f_oneway(*province_groups)

In [31]:
gender_table = pd.crosstab(df['Gender'], df['HasClaim'])
chi2, gender_p_value, dof, expected = stats.chi2_contingency(gender_table)

In [32]:
results = pd.DataFrame({
    "Hypothesis": [
        "Province vs Risk",
        "Gender vs Risk"
    ],
    "Test": [
        "ANOVA",
        "Chi-square"
    ],
    "P-value": [
        province_p_value,
        gender_p_value
    ]
})

results

         Hypothesis        Test   P-value
0  Province vs Risk       ANOVA  0.076083
1    Gender vs Risk  Chi-square  0.963831

In [33]:
top_zips = df['ZipCode'].value_counts().index[:2]

group_a = df[df['ZipCode'] == top_zips[0]]['HasClaim']
group_b = df[df['ZipCode'] == top_zips[1]]['HasClaim']

In [34]:
from scipy import stats

t_stat, zip_p_value = stats.ttest_ind(group_a, group_b)

print("T-statistic:", t_stat)
print("P-value:", zip_p_value)

T-statistic: -1.2905634290883656
P-value: 0.19705902122827368

In [35]:
results = pd.DataFrame({
    "Hypothesis": [
        "Province vs Risk",
        "Gender vs Risk",
        "ZipCode vs Risk"
    ],
    "Test": [
        "ANOVA",
        "Chi-square",
        "T-test"
    ],
    "P-value": [
        province_p_value,
        gender_p_value,
        zip_p_value
    ]
})

results

         Hypothesis        Test   P-value
0  Province vs Risk       ANOVA  0.076083
1    Gender vs Risk  Chi-square  0.963831
2   ZipCode vs Risk      T-test  0.197059

In [36]:
results["Decision"] = results["P-value"].apply(
    lambda p: "Reject H0" if p < 0.05 else "Fail to Reject H0"
)

results

         Hypothesis        Test   P-value           Decision
0  Province vs Risk       ANOVA  0.076083  Fail to Reject H0
1    Gender vs Risk  Chi-square  0.963831  Fail to Reject H0
2   ZipCode vs Risk      T-test  0.197059  Fail to Reject H0

In [37]:
results

         Hypothesis        Test   P-value           Decision
0  Province vs Risk       ANOVA  0.076083  Fail to Reject H0
1    Gender vs Risk  Chi-square  0.963831  Fail to Reject H0
2   ZipCode vs Risk      T-test  0.197059  Fail to Reject H0

Province vs Risk
If Reject H0 → Provinces have different risk levels → pricing should vary by region
If Fail → No strong regional difference → uniform pricing acceptable

In [38]:
from scipy import stats
import pandas as pd

def chi_square_test(df, col1, col2):
    table = pd.crosstab(df[col1], df[col2])
    chi2, p, dof, exp = stats.chi2_contingency(table)
    return chi2, p

def t_test(group1, group2):
    return stats.ttest_ind(group1, group2)

def anova_test(*groups):
    return stats.f_oneway(*groups)